name: Build PR docker image to dockerhub

on:
  pull_request_review:
    types: [submitted]

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request && 
      github.event.review.body == '/build'
    environment:
      name: staging
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.10.6
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image to dockerhub repository with PR number
        if: ${{ github.event.pull_request.number != '' }}
        run: |
          "${GITHUB_WORKSPACE}/build/build_and_push.sh" oscarzhou pr$GITHUB_PR_NUMBER